#ifndef BASE_SYNCHRONIZATION_SYNCHRONIZATION_HELPERS_H_
#define BASE_SYNCHRONIZATION_SYNCHRONIZATION_HELPERS_H_

namespace base {
enum class ThreadMode {
  kUsingCpp,
  kUsingPthread,
};
}

#endif  // BASE_SYNCHRONIZATION_SYNCHRONIZATION_HELPERS_H_
