#ifndef BASE_SYNCHRONIZATION_SYNCHRONIZATION_HELPERS_H
#define BASE_SYNCHRONIZATION_SYNCHRONIZATION_HELPERS_H

enum class ThreadMode {
    kUsingCpp,
    kUsingPthread,
};

#endif //BASE_SYNCHRONIZATION_SYNCHRONIZATION_HELPERS_H
