load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
  name = "producer_consumer",
  srcs = ["producer_consumer.cc"],
  deps = ["//base:base"],
)
cc_binary(
  name = "run_loop",
  srcs = ["run_loop.cc"],
  deps = ["//base:base"],
)
cc_binary(
  name = "task_posting",
  srcs = ["task_posting.cc"],
  deps = ["//base:base"],
)
